Make e Use Bash In Case Python is Messed Up

diff --git a/bin/e b/bin/e
--- a/bin/e
+++ b/bin/e
@@ -1,31 +1,33 @@
-#!/usr/bin/env -S python3 -I
+#!/bin/bash
 
-import sys
-import os
-import re
+set -e
 
-try:
-    editor = os.environ['EDITOR']
-except KeyError:
-    sys.exit('EDITOR is not set')
+if [ -z ${EDITOR+x} ]
+then
+    echo "ERROR: EDITOR is not set" 1>&2
+    exit 1
+fi
 
-sh_bool = {'true': True, 'false': False}
-try:
-    editor_is_vi = sh_bool[os.environ['IGTD_EDITOR_IS_VI']]
-except KeyError:
-    sys.exit('IGTD_EDITOR_IS_VI not set or not valid')
+if [ -z ${IGTD_EDITOR_IS_VI+x} ]
+then
+    echo "ERROR: IGTD_EDITOR_IS_VI is not set" 1>&2
+    exit 1
+fi
 
-regex = re.compile(r'(.*):(\d+)')
-args = [editor]
-if editor_is_vi:
-    for arg in sys.argv[1:]:
-        m = regex.match(arg)
-        if m:
-            args.append(m.group(1))
-            args.append('+' + m.group(2))
-        else:
-            args.append(arg)
-else:
-    args.extend(sys.argv[1:])
+if $IGTD_EDITOR_IS_VI
+then
+    args=()
+    regex="(.+):([0-9]+)"
+    for arg
+    do
+        if [[ $arg =~ $regex ]]
+        then
+            args+=("${BASH_REMATCH[1]}" "+${BASH_REMATCH[2]}")
+        else
+            args+=("$arg")
+        fi
+    done
+    exec $EDITOR "${args[@]}"
+fi
 
-os.execvp(editor, args)
+exec $EDITOR "$@"
